version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-browsers
      - image: buildpack-deps:trusty
    
    working_directory: ~/repo

    steps:
      - checkout
      # - run: 
      #     name: Backend Lint
      #     command: |
      #       cd backend && npm run lint
      - run: 
          name: Frontend build
          command: |
            cd frontend && npm install
      # - run: 
      #     name: Frontend Lint
      #     command: |
      #       cd frontend && npm run lint
      # - run: 
      #     name: Frontend Build
      #     command: |
      #       cd frontend && ng build
      - run: 
          name: Backend build
          command: |
            cd backend && npm install
      # - run: 
      #     name: Backend start
      #     command: |
      #       cd backend && npm start
      - run:
          name: Deploy Dev to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git dev